
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Crypteron.SampleApps.ConsoleCipherDbEf6DbFirst
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public int OrderId { get; set; }

    public string OrderItem { get; set; }

    public Nullable<System.DateTime> Timestamp { get; set; }

    public string CustomerName { get; set; }

    public byte[] Secure_SocialSecurityNumber { get; set; }

    public string Secure_LegacyPIN { get; set; }

    public string SecureSearch_CreditCardNumber { get; set; }

}

}
